name: GitHub Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *' # har kuni yarim kechada ishlaydi
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: platane/snk@v1
        with:
          github_user_name: Asvell-ai       # GitHub username
          svg_out_path: output/github-contribution-grid-snake.svg  # SVG qayerga hosil boâ€˜ladi
