name: GitHub Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *' # har kuni yarim kechada ishlaydi
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: platane/snk@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_repo: ${{ github.repository }}
          color: "4e54c8" # Snake rangi
